update

diff --git a/usr/share/archlinux-tweak-tool/data/arco/bin/get-linux-cachyos-from-chaotic-repo b/usr/share/archlinux-tweak-tool/data/arco/bin/get-linux-cachyos-from-chaotic-repo
--- a/usr/share/archlinux-tweak-tool/data/arco/bin/get-linux-cachyos-from-chaotic-repo
+++ b/usr/share/archlinux-tweak-tool/data/arco/bin/get-linux-cachyos-from-chaotic-repo
@@ -1,15 +1,15 @@
 #!/bin/bash
 #set -e
 ##################################################################################################################
-# Author 	: Erik Dubois
+# Author    : Erik Dubois
 # Website   : https://www.erikdubois.be
 # Website   : https://www.alci.online
-# Website	: https://www.arcolinux.info
-# Website	: https://www.arcolinux.com
-# Website	: https://www.arcolinuxd.com
-# Website	: https://www.arcolinuxb.com
-# Website	: https://www.arcolinuxiso.com
-# Website	: https://www.arcolinuxforum.com
+# Website   : https://www.arcolinux.info
+# Website   : https://www.arcolinux.com
+# Website   : https://www.arcolinuxd.com
+# Website   : https://www.arcolinuxb.com
+# Website   : https://www.arcolinuxiso.com
+# Website   : https://www.arcolinuxforum.com
 ##################################################################################################################
 #
 #   DO NOT JUST RUN THIS. EXAMINE AND JUDGE. RUN AT YOUR OWN RISK.
@@ -26,18 +26,31 @@
 #tput setaf 8 = light blue
 ##################################################################################################################
 
-#Automount shared folders for virtualbox
-user=$( who | cut -d ' ' -f1 | uniq)
-sudo gpasswd -a $user vboxsf
-sudo systemctl enable vboxservice.service
-sudo systemctl start vboxservice.service
-echo "##############################################"
-echo "Now log out and log back in"
-echo "If you have set virtualbox to share a folder"
-echo "with automount, it will appear in the"
-echo "filemanager at next login"
-echo "##############################################"
+sudo cp -v /etc/pacman.conf /etc/pacman.conf.script
 
+sh /usr/local/bin/arcolinux-fix-pacman-conf
+sh /usr/local/bin/toggle-arcolinux-repo
+
+# Set the file path
+FILE="/etc/pacman.conf"
+
+# Search for "chaotic-aur" in the specified file
+if ! grep -q "chaotic-aur" "$FILE"; then
+    echo "Adding chaotic-aur repository to $FILE"
+    # Append the configuration for chaotic-aur to the file
+    {
+echo ""
+echo "[chaotic-aur]"
+echo "SigLevel = Required DatabaseOptional"
+echo "Include = /etc/pacman.d/chaotic-mirrorlist"
+    } | sudo tee -a "$FILE"
+fi
+
+sudo pacman -Sy linux-cachyos linux-cachyos-headers --noconfirm --needed
+
+sudo cp -v /etc/pacman.conf.script /etc/pacman.conf
+
+echo
 echo "###############################################################################"
 echo "###                DONE - YOU CAN CLOSE THIS WINDOW                        ####"
 echo "###############################################################################"
