Added conditions, after further testing on x11

diff --git a/usr/bin/archlinux-tweak-tool b/usr/bin/archlinux-tweak-tool
--- a/usr/bin/archlinux-tweak-tool
+++ b/usr/bin/archlinux-tweak-tool
@@ -1,11 +1,29 @@
 #!/usr/bin/env sh
 
-# polkit agent should prompt for root password
 # this script should not be run as root or run in a tty session
+# polkit agent should prompt for root password
 
+echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
 test $(whoami) == "root" && echo "[ERROR] Do not run this script as root." && exit 1
 test -z $DISPLAY && echo "[ERROR] DISPLAY variable is not set." && exit 1
 
-xauth gen $DISPLAY &> /dev/null
+session=$(loginctl show-session $(loginctl|grep $(whoami) | awk '{print $1}') -p Type | awk -F= '{print $2}' | grep "x11\|wayland")
 
+echo "[INFO] Display = $DISPLAY"
+echo "[INFO] Session = $session"
+
+case "$session" in
+  "wayland")
+    xauth gen $DISPLAY &> /dev/null
+  ;;
+  "x11")
+    test -s $HOME/.Xauthority || echo "[ERROR] XAuth cookie not setup, logout/reboot to fix this." || exit 1
+
+    test -z $(xauth list | awk -F"MIT-MAGIC-COOKIE-1" '{print $2}' | tr -d ' ') || echo "[INFO] XAuth cookie is already setup."
+    test -z $(xauth list | awk -F"MIT-MAGIC-COOKIE-1" '{print $2}' | tr -d ' ') && echo "[ERROR] XAuth cookie not setup, logout/reboot to fix this." && exit 1
+  ;;
+esac
+echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
+
+echo "[INFO] Starting ArchLinux Tweak Tool"
 pkexec '/usr/share/archlinux-tweak-tool/archlinux-tweak-tool.py'
