Terminate script if session is not x11/wayland

diff --git a/usr/bin/archlinux-tweak-tool b/usr/bin/archlinux-tweak-tool
--- a/usr/bin/archlinux-tweak-tool
+++ b/usr/bin/archlinux-tweak-tool
@@ -22,6 +22,10 @@ case "$session" in
     test -z $(xauth list | awk -F"MIT-MAGIC-COOKIE-1" '{print $2}' | tr -d ' ') || echo "[INFO] XAuth cookie is already setup."
     test -z $(xauth list | awk -F"MIT-MAGIC-COOKIE-1" '{print $2}' | tr -d ' ') && echo "[ERROR] XAuth cookie not setup, logout/reboot to fix this." && exit 1
   ;;
+  *)
+    echo "[ERROR] Cannot verify session for user."
+    exit 1
+  ;;
 esac
 echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
 
