conform layout - error message on x11 gone

diff --git a/usr/bin/archlinux-tweak-tool b/usr/bin/archlinux-tweak-tool
--- a/usr/bin/archlinux-tweak-tool
+++ b/usr/bin/archlinux-tweak-tool
@@ -3,7 +3,7 @@
 # this script should not be run as root or run in a tty session
 # polkit agent should prompt for root password
 
-echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
+echo "---------------------------------------------------------------------------"
 
 test $(whoami) == "root" && echo "[ERROR] Do not run this script as root." && exit 1
 test -z $DISPLAY && echo "[ERROR] DISPLAY variable is not set." && exit 1
@@ -12,26 +12,27 @@ session=$(loginctl show-session $(loginctl|grep $(whoami) | awk '{print $1}') -p
 
 test -z "$session" && echo "[ERROR] Failed to verify session for user." && exit 1
 
-echo "[INFO] Display = $DISPLAY"
-echo "[INFO] Session = $session"
-
 xauth_file=$(xauth info | awk -F"Authority file:" '{print $2}' | tr -d ' ')
 test -s "$xauth_file" || touch "$xauth_file"
 
 case "$session" in
   "wayland")
     xauth gen $DISPLAY &> /dev/null
+    echo "[INFO] Display = $DISPLAY"
+    echo "[INFO] Session = $session"
   ;;
   "x11")
-    test -z $(xauth list | awk -F"MIT-MAGIC-COOKIE-1" '{print $2}' | tr -d ' ') || echo "[INFO] XAuth cookie is already setup."
-    test -z $(xauth list | awk -F"MIT-MAGIC-COOKIE-1" '{print $2}' | tr -d ' ') && echo "[ERROR] XAuth cookie not setup, logout/reboot to fix this." && exit 1
+    echo "[INFO] Display = $DISPLAY"
+    echo "[INFO] Session = $session"
+    #test -z $(xauth list | awk -F"MIT-MAGIC-COOKIE-1" '{print $2}' | tr -d ' ') || echo "[INFO] XAuth cookie is already setup."
+    #test -z $(xauth list | awk -F"MIT-MAGIC-COOKIE-1" '{print $2}' | tr -d ' ') && echo "[ERROR] XAuth cookie not setup, logout/reboot to fix this." && exit 1
   ;;
   *)
     echo "[ERROR] Cannot verify session for user."
     exit 1
   ;;
 esac
-echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
+echo "---------------------------------------------------------------------------"
 
 echo "[INFO] Starting ArchLinux Tweak Tool"
 pkexec '/usr/share/archlinux-tweak-tool/archlinux-tweak-tool.py'
