Testing changes to fix opening ATT on Sway.

diff --git a/usr/bin/archlinux-tweak-tool b/usr/bin/archlinux-tweak-tool
--- a/usr/bin/archlinux-tweak-tool
+++ b/usr/bin/archlinux-tweak-tool
@@ -1,10 +1,25 @@
-#!/usr/bin/env bash
+#!/usr/bin/env sh
 
-# ATT fails to startup on Hyprland, added a few tests to see if the Xauthority file is present
+test $(whoami) == "root" && echo "[ERROR] Do not run this script as root." && exit 1
 
-# test whether DISPLAY env is set, terminate if isn't
-test -z $(echo "$DISPLAY") && echo "DISPLAY is not set, terminating." && exit 1
-# test there is an Xauthority to work with, else generate one
-test $(xauth list | grep -w "MIT-MAGIC-COOKIE" | wc -l) -gt 0 || xauth gen $DISPLAY > "$HOME/.Xauthority"
+session=$(loginctl show-session $(loginctl|grep $(whoami) | awk '{print $1}') -p Type | awk -F= '{print $2}' | grep "x11\|wayland")
 
-pkexec '/usr/share/archlinux-tweak-tool/archlinux-tweak-tool.py'
+case "$session" in
+    "wayland")
+        echo "[INFO] User $(whoami) is on $session"
+        xauth gen $DISPLAY &> /dev/null
+
+    ;;
+    "x11")
+        echo "[INFO] User $(whoami) is on $session"
+
+    ;;
+esac
+
+
+
+echo "DISPLAY = $DISPLAY"
+
+#pkexec '/usr/share/archlinux-tweak-tool/archlinux-tweak-tool.py'
+
+pkexec '/mnt/shared/share/archlinux-tweak-tool/archlinux-tweak-tool.py'
